users/urls.py
"""Defines URL patterns for users"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
	# Login page
	path('login/', 
		auth_views.LoginView.as_view(template_name='users/login.html'), 
		name='login'),
		
	# Logout page
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	
	# Registration page
	path('register/', views.register, name='register'),
]

weblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('weblogs.urls')),
]

weblogs/urls.py
"""Defines URL patterns for weblogs."""

from django.urls import path

from . import views

app_name = 'weblogs'
urlpatterns = [
	# Home page
	path('', views.index, name='index'),
	
	# Page for adding a new post
	path('new_post/', views.new_post, name='new_post'),
	
	# Page for viewing posts
	path('my_posts/', views.my_posts, name='my_posts'),
	
	# Page for editing posts
	path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
	
	# For deleting a post.
	path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
]

users/models.py
from django.db import models

# Create your models here.

weblogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
	"""A post for any site visitors to see."""
	title = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	body = models.TextField()
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	
	def __str__(self):
		"""Return a string representation of the model."""
		return self.title

weblogs/forms.py
from django import forms

from .models import BlogPost

class BlogPostForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields = ['title', 'body']
		labels = {'title': 'Title', 'body': ''}
		widgets = {'body': forms.Textarea(attrs={'cols': 80})}

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

def register(request):
	"""Register a new user."""
	if request.method != 'POST':
		# Display blank registration form.
		form = UserCreationForm()
	else:
		# Process completed form.
		form = UserCreationForm(data=request.POST)
		
		if form.is_valid():
			new_user = form.save()
			# Log the user in and then redirect to home page.
			authenticated_user = authenticate(username=new_user.username,
				password=request.POST['password1'])
			login(request, authenticated_user)
			return HttpResponseRedirect(reverse('weblogs:my_posts'))
			
	context = {'form': form}
	return render(request, 'users/register.html', context)

weblogs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import BlogPost
from .forms import BlogPostForm

def index(request):
	"""The home page for Weblog. Shows all blog posts."""
	posts = BlogPost.objects.order_by('-date_added')
	context = {'posts': posts}
	return render(request, 'weblogs/index.html', context)

@login_required
def new_post(request):
	"""The page for a user to add a new post."""
	if request.method != 'POST':
		form = BlogPostForm()
	else:
		form = BlogPostForm(data=request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('weblogs:index'))
			
	context = {'form': form}
	return render(request, 'weblogs/new_post.html', context)
	
@login_required
def my_posts(request):
	"""The page for a user to view and edit their own posts."""
	posts = BlogPost.objects.filter(owner=request.user).order_by('-date_added')
	context = {'posts': posts}
	return render(request, 'weblogs/my_posts.html', context)

@login_required
def edit_post(request, post_id):
	"""The page for a user to edit a selected post."""
	post = BlogPost.objects.get(id=post_id)
	# Make sure the post belongs to the user.
	if post.owner != request.user:
		raise Http404
	
	if request.method != 'POST':
		# Initial request; pre-fill the form with the current post.
		form = BlogPostForm(instance=post)
	else:
		# POST data submitted; change the post.
		form = BlogPostForm(instance=post, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('weblogs:my_posts'))
			
	context = {'post': post, 'form': form}
	return render(request, 'weblogs/edit_post.html', context)

@login_required
def delete_post(request, post_id):
	"""This is for deleting a selected post."""
	post = BlogPost.objects.get(id=post_id)
	if post.owner != request.user:
		raise Http404
	post.delete()
	return HttpResponseRedirect(reverse('weblogs:my_posts'))
	posts = BlogPost.objects.order_by('-date_added')
	context = {'posts': posts}
	return render(request, 'weblogs/my_posts.html', context)
	

users/templates/users/login.html
{% extends "weblogs/base.html" %}

{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account</h2>
{% endblock header %}


{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
    
    <input type="hidden" name="next" value="{% url 'weblogs:index' %}" />  
  </form>
  
{% endblock content %}

users/templates/users/register.html
{% extends "weblogs/base.html" %}

{% load bootstrap3 %}

{% block header %}
  <h2>Register for an account</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">register</button>
    {% endbuttons %}
    
    <input type="hidden" name="next" value="{% url 'weblogs:my_posts' %}" />
  </form>

{% endblock content %}

weblogs/templates/weblogs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Weblog</title>
    
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    
  </head>
  
  <body>
  
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
      
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'weblogs:index' %}">
              Weblog</a>
          </div>
          
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'weblogs:my_posts' %}">My Posts</a></li>
            </ul>
            
            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                <li><a>Hello, {{ user.username }}</a></li>
                <li><a href="{% url 'users:logout' %}">log out</a></li>
              {% else %}
                <li><a href="{% url 'users:register' %}">register</a></li>
                <li><a href="{% url 'users:login' %}">login</a></li>
              {% endif %}
            </ul>
          </div><!--/.nav collapse -->
          
        </div>
      </nav>
      
      <div class="container">
		  
        <div class="page-header">
          {% block header %}{% endblock header %}
        </div>
        <div>
          {% block content %}{% endblock content %}
        </div>
      
    </div> <!-- /container -->
    
  </body>
</html>

weblogs/templates/weblogs/edit_post.html
{% extends "weblogs/base.html" %}

{% load bootstrap3 %}

{% block header %}
  <h2>Edit post:</h2>
{% endblock header %}

{% block content %}
  
  <form action="{% url 'weblogs:edit_post' post.id %}" method='post'
	class="form">
	
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">save changes</button>
    {% endbuttons %}
    
  </form>
  
{% endblock content %}

weblogs/templates/weblogs/index.html
{% extends "weblogs/base.html" %}

{% block header %}
  <div class='jumbotron'>
    <h1>Share your interests.</h1>
  </div>
{% endblock header %}

{% block content %}
  

  {% if user.is_authenticated %}
    <h2>
      <a href="{% url 'weblogs:new_post' %}">Create a post</a> to share
      your ideas and stories with others.
    </h2>
  {% else %}
    <h2>
      <a href="{% url 'users:register' %}">Register for an account</a>
      to create your own posts to share ideas, promote a cause, or relate
      experiences to others.
    </h2>
  {% endif %}
  
  <ul>
    {% for post in posts %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>
            {{ post }}
            <small>
		      {{ post.owner }} -
              {{ post.date_added|date:'M d, Y H:i' }}
            </small>
          </h3>
        </div>
        <div class="panel-body">
	      {{ post.body|linebreaks }} 
        </div>
      </div> <!-- panel -->
	
	  {% empty %}
	    {% if user.is_authenticated %}
          <h3>There are no posts yet. Be the first to share.</h3>
        {% else %}
          <h3>
	        There are no posts yet. Register to be the first to make a post.</li>
          </h3>
        {% endif %}
    {% endfor %}
  </ul>
  
{% endblock content %}

weblogs/templates/weblogs/my_posts.html
{% extends "weblogs/base.html" %}

{% block header %}
  <h1>My Posts</h1>
{% endblock header %}

{% block content %}

  <ul>
    {% for post in posts %}
      <a href="{% url 'weblogs:edit_post' post.id %}">edit post</a> -
      <a href="{% url 'weblogs:delete_post' post.id %}">delete</a>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>
            {{ post }}
            <small>
              {{ post.date_added|date:'M d, Y H:i' }}
            </small>
          </h3>
        </div>
        <div class="panel-body">
	      {{ post.body|linebreaks }} 
        </div>
      </div> <!-- panel -->

    {% empty %}
      <h3>
        You do not have any blog posts yet- create a new one
        <a href="{% url 'weblogs:new_post' %}">here</a>.
      </h3>
    {% endfor %}
  </ul>
  
{% endblock content %}

weblogs/templates/weblogs/new_post.html
{% extends "weblogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new post:</h2>
{% endblock header %}

{% block content %}

  <form action="{% url 'weblogs:new_post' %}" method='post'
    class="form">
 
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">add post</button>
    {% endbuttons %}
    
  </form>
  
{% endblock content %}